{% set name = "bliss" %}
{% set version = "0.77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://users.aalto.fi/~tjunttil/bliss/downloads/bliss-{{ version }}.zip
  sha256: acc8b98034f30fad24c897f365abd866c13d9f1bb207e398d0caf136875972a4

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - autoconf
    - automake
    - make

test:
  commands:
    - test -f "$PREFIX/include/bliss/graph.hh"
    - test -f "$PREFIX/lib/libbliss${SHLIB_EXT}"

about:
  home: http://www.tcs.hut.fi/Software/bliss/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'A Tool for Computing Automorphism Groups and Canonical Labelings of Graphs'
  doc_url: http://www.tcs.hut.fi/Software/bliss/doxy/index.html

extra:
  recipe-maintainers:
    - isuruf
